add_header Cross-Origin-Resource-Policy "cross-origin" always;
add_header Access-Control-Allow-Origin "*" always;
add_header Access-Control-Allow-Methods "GET, OPTIONS, PUT, POST, PATCH, DELETE" always;
add_header Access-Control-Allow-Headers "*" always;
add_header Access-Control-Max-Age "100" always;
add_header Vary "Origin" always;
